params = {'line_width': 74}

valid_nucleotide = set(['a',
                        'g',
                        'c',
                        't',
                        'u',
                        'r',
                        'y',
                        'm',
                        'k',
                        's',
                        'w',
                        'b',
                        'd',
                        'h',
                        'v',
                        'n'])

valid_aa = set(['Ala',
                'Cys',
                'Asp',
                'Glu',
                'Phe',
                'Gly',
                'His',
                'Ile',
                'Lys',
                'Leu',
                'Met',
                'Asn',
                'Pro',
                'Gln',
                'Arg',
                'Ser',
                'Thr',
                'Val',
                'Trp',
                'Tyr',
                'Asx',
                'Glx',
                'Xaa'])

codon_dict = {'ttt': 'Phe',
              'ttc': 'Phe',
              'tta': 'Leu',
              'ttg': 'Leu',
              'ctt': 'Leu',
              'ctc': 'Leu',
              'cta': 'Leu',
              'ctg': 'Leu',
              'att': 'Ile',
              'atc': 'Ile',
              'ata': 'Ile',
              'atg': 'Met',
              'gtt': 'Val',
              'gtc': 'Val',
              'gta': 'Val',
              'gtg': 'Val',
              'tct': 'Ser',
              'tcc': 'Ser',
              'tca': 'Ser',
              'tcg': 'Ser',
              'cct': 'Pro',
              'ccc': 'Pro',
              'cca': 'Pro',
              'ccg': 'Pro',
              'act': 'Thr',
              'acc': 'Thr',
              'aca': 'Thr',
              'acg': 'Thr',
              'gct': 'Ala',
              'gcc': 'Ala',
              'gca': 'Ala',
              'gcg': 'Ala',
              'tat': 'Tyr',
              'tac': 'Tyr',
              'taa': 'Ter',
              'tag': 'Ter',
              'cat': 'His',
              'cac': 'His',
              'caa': 'Gln',
              'cag': 'Gln',
              'aat': 'Asn',
              'aac': 'Asn',
              'aaa': 'Lys',
              'aag': 'Lys',
              'gat': 'Asp',
              'gac': 'Asp',
              'gaa': 'Glu',
              'gag': 'Glu',
              'tgt': 'Cys',
              'tgc': 'Cys',
              'tga': 'Ter',
              'tgg': 'Trp',
              'cgt': 'Arg',
              'cgc': 'Arg',
              'cga': 'Arg',
              'cgg': 'Arg',
              'agt': 'Ser',
              'agc': 'Ser',
              'aga': 'Arg',
              'agg': 'Arg',
              'ggt': 'Gly',
              'ggc': 'Gly',
              'gga': 'Gly',
              'ggg': 'Gly'}

aa_1char_3char_dict = {'G': 'Gly',
                       'A': 'Ala',
                       'L': 'Leu',
                       'M': 'Met',
                       'F': 'Phe',
                       'W': 'Trp',
                       'K': 'Lys',
                       'Q': 'Gln',
                       'E': 'Glu',
                       'S': 'Ser',
                       'P': 'Pro',
                       'V': 'Val',
                       'I': 'Ile',
                       'C': 'Cys',
                       'Y': 'Tyr',
                       'H': 'His',
                       'R': 'Arg',
                       'N': 'Asn',
                       'D': 'Asp',
                       'T': 'Thr',
                       'X': 'Xaa'}


